# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6beb96967ef47bcb7e617318972c4a97d6ec6b9720cfe38f3e86af62ae81cdaf240a3a9c2a713ad8dde075230a4b185af9e2e0d8e9b866a784cf261bae277a15

test:
  secret_key_base: 060e6afd7ff1e3e23f8a5af534205a8154ccd1973638f9d8ccefda8ec94c3677503b515296a52c211b980a4b3f1b4842eeb8fe339f813f6e7e24bd554795e982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
